<?php


namespace App\Garmin\Stock\ResponseMap;

use App\Mapper\Type\Response\EntityFieldIndicator as EFI;
use App\Mapper\Type\Response\MapReverser;

class Activity extends MapReverser
{
    public function __construct()
    {
        $this->responseMap = [
            'activityId' => new EFI('bigint', 'activityId', false, 3799835428),
            'activityName' => (new EFI('string', 'activityName'))->setConvertFunction('dumpp'),
            'description' => (new EFI('string', 'description')),
            'startTimeLocal' => (new EFI('datetime', 'startTimeLocal', false, '2019-06-30 20:56:34'))->setConvertFunction('strToTime'),
            'startTimeGMT' => (new EFI('datetime', 'startTimeGMT', false, '2019-06-30 20:56:34'))->setConvertFunction('strToTime'),
            'activityType' =>
                array(
                    'typeId' => new EFI('integer', 'activityTypeId', true, '1'),
                    'typeKey' => new EFI('string', 'activityTypeKey', true, 'running'),
                    'parentTypeId' => new EFI('integer', 'activityParentTypeId', true, '1'),
                    'sortOrder' => 3,
                ),
            'eventType' =>
                array(
                    'typeId' => 9,
                    'typeKey' => 'uncategorized',
                    'sortOrder' => 10,
                ),
            'comments' => new EFI('string', 'comments', true),
            'parentId' => NULL,
            'distance' => new EFI('float', 'distance', false, '8560.76'),
            'duration' => new EFI('float', 'duration', false, '2681.656'),
            'elapsedDuration' => new EFI('float', 'elapsedDuration', true, '2891.998'),
            'movingDuration' => new EFI('float', 'movingDuration', true, '2670.0'),
            'elevationGain' => new EFI('float', 'elevationGain', true, '27.0'),
            'elevationLoss' => new EFI('float', 'elevationLoss', true, '27.0'),
            'averageSpeed' => new EFI('float', 'averageSpeed', true, '3.1500000953674316'),
            'maxSpeed' => new EFI('float', 'maxSpeed', true, '4.085999965667725'),
            'startLatitude' => new EFI('float', 'startLatitude', true, '50.54094795137644'),
            'startLongitude' => new EFI('float', 'startLongitude', true, '22.085774475708604'),
            'hasPolyline' => true,
            'ownerId' => 9358035,
            'ownerDisplayName' => new EFI('string', 'userDisplayName', 'lbrzozowski'),
            'ownerFullName' => new EFI('string', 'ownerFullName', 'Łukasz Brzozowski'),
            'ownerProfileImageUrlSmall' => 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/68a227d2-7e93-4655-a981-73ec25518050-9358035.png',
            'ownerProfileImageUrlMedium' => 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/ed9baa89-2b2d-4616-a8d2-b27f3f4d231d-9358035.png',
            'ownerProfileImageUrlLarge' => 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/5a9aaf8b-4c2d-44cc-9447-dbc296a1e95e-9358035.png',
            'ownerProfilePk' => NULL,
            'calories' => new EFI('float', 'calories', '2670.0'),
            'averageHR' => new EFI('float', 'averageHR', '2670.0'),
            'maxHR' => new EFI('float', 'maxHR', '2670.0'),
            'averageRunningCadenceInStepsPerMinute' => new EFI('float', 'averageRunCadence', '2670.0'),
            'maxRunningCadenceInStepsPerMinute' => new EFI('float', 'maxRunCadence', '2670.0'),
            'averageBikingCadenceInRevPerMinute' => NULL,
            'maxBikingCadenceInRevPerMinute' => NULL,
            'averageSwimCadenceInStrokesPerMinute' => NULL,
            'maxSwimCadenceInStrokesPerMinute' => NULL,
            'averageSwolf' => new EFI('float', 'averageSwolf', '2670.0'),
            'activeLengths' => NULL,
            'steps' => new EFI('integer', 'steps', '2670'),
            'conversationUuid' => NULL,
            'conversationPk' => NULL,
            'numberOfActivityLikes' => new EFI('integer', 'numberOfActivityLikes', '2670'),
            'numberOfActivityComments' => NULL,
            'likedByUser' => NULL,
            'commentedByUser' => NULL,
            'activityLikeDisplayNames' => NULL,
            'activityLikeFullNames' => NULL,
            'requestorRelationship' => NULL,
            'userRoles' =>
                array(
                    0 => 'ROLE_CONNECTUSER',
                    1 => 'ROLE_FITNESS_USER',
                    2 => 'ROLE_WELLNESS_USER',
                    3 => 'ROLE_OUTDOOR_USER',
                    4 => 'ROLE_CONNECT_2_USER',
                ),
            'privacy' =>
                array(
                    'typeId' => 4,
                    'typeKey' => 'groups',
                ),
            'userPro' => false,
            'courseId' => NULL,
            'poolLength' => NULL,
            'unitOfPoolLength' => NULL,
            'hasVideo' => false,
            'videoUrl' => NULL,
            'timeZoneId' => 124,
            'beginTimestamp' => 1561920994000,
            'sportTypeId' => 1,
            'avgPower' => NULL,
            'maxPower' => NULL,
            'aerobicTrainingEffect' => new EFI('float', 'trainingEffect', true, '3.0'),
            'anaerobicTrainingEffect' => new EFI('float', 'trainingEffectAnaerobic', true, '3.0'),
            'strokes' => NULL,
            'normPower' => NULL,
            'leftBalance' => NULL,
            'rightBalance' => NULL,
            'avgLeftBalance' => NULL,
            'max20MinPower' => NULL,
            'avgVerticalOscillation' => new EFI('float', 'verticalOscillation', true, '11.990000152587891'),
            'avgGroundContactTime' => new EFI('float', 'groundContactTime', true, '254.89999389648438'),
            'avgStrideLength' => new EFI('float', 'strideLength', true, '124.68000488281251'),
            'avgFractionalCadence' => NULL,
            'maxFractionalCadence' => NULL,
            'trainingStressScore' => NULL,
            'intensityFactor' => NULL,
            'vO2MaxValue' => new EFI('float', 'vO2MaxValue', true, '53.0'),
            'avgVerticalRatio' => new EFI('float', 'verticalRatio', '9.452140'),
            'avgGroundContactBalance' => new EFI('float', 'avgGroundContactBalance', true, '254.89999389648438'),
            'lactateThresholdBpm' => new EFI('float', 'lactateThresholdBpm', true, '?'),
            'lactateThresholdSpeed' => new EFI('float', 'lactateThresholdSpeed', true, '?'),
            'maxFtp' => NULL,
            'avgStrokeDistance' => NULL,
            'avgStrokeCadence' => NULL,
            'maxStrokeCadence' => NULL,
            'workoutId' => 149791636,
            'avgStrokes' => NULL,
            'minStrokes' => NULL,
            'deviceId' => new EFI('float', 'deviceId', '26702354'),
            'minTemperature' => new EFI('float', 'minTemperature', true, '2670.0'),
            'maxTemperature' => new EFI('float', 'maxTemperature', true, '2670.0'),
            'minElevation' => new EFI('float', 'minElevation', true, '13639.999389648438'),
            'maxElevation' => new EFI('float', 'maxElevation', true, '2670.0'),
            'avgDoubleCadence' => NULL,
            'maxDoubleCadence' => 157.0,
            'summarizedExerciseSets' =>
                array(),
            'maxDepth' => NULL,
            'avgDepth' => NULL,
            'surfaceInterval' => NULL,
            'startN2' => NULL,
            'endN2' => NULL,
            'startCns' => NULL,
            'endCns' => NULL,
            'summarizedDiveInfo' =>
                array(
                    'weight' => NULL,
                    'weightUnit' => NULL,
                    'visibility' => NULL,
                    'visibilityUnit' => NULL,
                    'surfaceCondition' => NULL,
                    'current' => NULL,
                    'waterType' => NULL,
                    'waterDensity' => NULL,
                    'summarizedDiveGases' =>
                        array(),
                    'totalSurfaceTime' => 0,
                ),
            'activityLikeAuthors' => NULL,
            'avgVerticalSpeed' => NULL,
            'maxVerticalSpeed' => 1.1999969482421875,
            'floorsClimbed' => NULL,
            'floorsDescended' => NULL,
            'manufacturer' => NULL,
            'diveNumber' => NULL,
            'locationName' => 'Stalowa Wola',
            'bottomTime' => NULL,
            'lapCount' => 20,
            'endLatitude' => NULL,
            'endLongitude' => NULL,
            'minAirSpeed' => NULL,
            'maxAirSpeed' => NULL,
            'avgAirSpeed' => NULL,
            'avgWindYawAngle' => NULL,
            'minCda' => NULL,
            'maxCda' => NULL,
            'avgCda' => NULL,
            'avgWattsPerCda' => NULL,
            'flow' => NULL,
            'grit' => NULL,
            'jumpCount' => NULL,
            'caloriesEstimated' => NULL,
            'caloriesConsumed' => NULL,
            'waterEstimated' => NULL,
            'waterConsumed' => NULL,
            'maxAvgPower_1' => NULL,
            'maxAvgPower_2' => NULL,
            'maxAvgPower_5' => NULL,
            'maxAvgPower_10' => NULL,
            'maxAvgPower_20' => NULL,
            'maxAvgPower_30' => NULL,
            'maxAvgPower_60' => NULL,
            'maxAvgPower_120' => NULL,
            'maxAvgPower_300' => NULL,
            'maxAvgPower_600' => NULL,
            'maxAvgPower_1200' => NULL,
            'maxAvgPower_1800' => NULL,
            'maxAvgPower_3600' => NULL,
            'maxAvgPower_7200' => NULL,
            'maxAvgPower_18000' => NULL,
            'excludeFromPowerCurveReports' => NULL,
            'totalSets' => NULL,
            'totalReps' => NULL,
            'minRespirationRate' => NULL,
            'maxRespirationRate' => NULL,
            'avgRespirationRate' => NULL,
            'trainingEffectLabel' => NULL,
            'activityTrainingLoad' => NULL,
            'avgFlow' => NULL,
            'avgGrit' => NULL,
            'minActivityLapDuration' => 0.6729999780654907,
            'startStress' => NULL,
            'endStress' => NULL,
            'differenceStress' => NULL,
            'aerobicTrainingEffectMessage' => NULL,
            'anaerobicTrainingEffectMessage' => NULL,
            'favorite' => false,
            'decoDive' => NULL,
            'pr' => false,
            'autoCalcCalories' => false,
            'parent' => false,
            'atpActivity' => false,
            'purposeful' => false,
            'elevationCorrected' => false,
        ];
        parent::__construct();
    }
}